### ISSUE TITLE
Have to save tiebreaker before submit

### ISSUE THREAD

**Issue by balexander82** [bduff9/nfl-meteor#18] opened 2016-08-24 02:45 UTC
Currently you have to save the tiebreaker score before submitting. Should you be able to submit without saving?

**Comment by bduff9** [comment] 2016-08-24 02:49
Its not that you have to save, its that the tiebreaker doesn't register until onBlur happens.  Typing in a value and clicking anywhere else on the page will allow it to work.  The problem is onkeyup causes performance issues so not sure there is a way around this.  Closing for now but if you have an idea, I'd be happy to consider it

**Closed by bduff9** 2016-08-24 02:49 UTC
Labels: bug, question
